### ISSUE TITLE
$ref value is not autocompleted in all required places

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#122]
`$ref` autocompletion does not work in the following case:

```yaml
definitions:
  Foo:
    type: object
    properties:
      prop:
        $ref: <cursor>
```
