### ISSUE TITLE
UI should support swagger split into more files

### ISSUE THREAD

**Issue by jimirocks** [zalando/intellij-swagger#151]
i.e.
```yaml
'/myPath':
    post:
      summary: schema in external file
      parameters:
        - name: external
          in: body
          required: true
          schema:
            $ref: 'test.yml'
```

And in `test.yml` in the same directory
```yaml
ExternalSchema:
  title: External schema not working
  type: object
```

The UI reports:
```Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: 'test.yml' basePath: 'undefined'```
