### ISSUE TITLE
$ref value is not autocompleted in `parameters` of `Path Item Object`

### ISSUE THREAD

**Issue by glukki** [zalando/intellij-swagger#152]
```yaml
  /course/{offeringId}:
    parameters:
      - $ref: '<cursor>'
```

Please notice, that references may link only to `Swagger Object`'s `parameters`: `#/parameters/...`

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object
