### ISSUE TITLE
`items` keys not always auto completed

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#157]
For example

```yaml
definitions:
  Definition:
    type: object
    properties:
      some_list:
        type: array
        items:
          <caret> // No auto completion here.
```
