### ISSUE TITLE
Autocomplete doesn't work for yaml split into multiple files

### ISSUE THREAD

**Issue by maarten00** [zalando/intellij-swagger#160]
I have a main file which contains three refs:

```
definitions:
  DossierComment:
    $ref: ./definitions/DossierComment.yml
  User:
    $ref: ./definitions/User.yml
paths:
  /dossier/{dossierId}/comments:
    $ref: ./paths/DossierComments.yml

```

Autocomplete works in this file. I can use cmd+click to view the files. Autocomplete does not work in the referenced files. I can fix it by adding `swagger: '2.0'` to the top, but this raises a syntax error:
![screen shot 2018-04-25 at 09 35 07](https://user-images.githubusercontent.com/1579711/39288588-dff9e5b2-4928-11e8-9c82-2593db6d885f.png)

Swagger UI can read these files just fine, so no issue there. I can fix the syntax error in my screenshot by indenting line 2:18 with one tab, autocomplete does work if I do that. But sadly, Swagger UI will no longer read the files properly.
