### ISSUE TITLE
Schema autocompletion improvements

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#209]
Auto completion does not suggest anything in the following cases:

```yaml
components:
  schemas:
    schema1:
      properties:
        prop1:
          <caret>
```

```yaml
components:
  schemas:
    schema1:
      allOf:
      - <caret>
```
