### ISSUE TITLE
$ref autocompletion improvements

### ISSUE THREAD

**Issue by semonte** [zalando/intellij-swagger#213]
Auto completion does not suggest anything in the following case:

```yaml
components:
  schemas:
    schema1:
      allOf:
      - $ref: <caret>
```
