### ISSUE TITLE
Autocomplete ref not working for separate file

### ISSUE THREAD

**Issue by WhoKnocks** [zalando/intellij-swagger#268]
Intellij does not suggest any components listed in another file.

See:
![image](https://user-images.githubusercontent.com/6548515/57614246-01035900-7579-11e9-8182-4d7b9c31c8ca.png)

While this is valid and intellij is able to navigate to it.
![image](https://user-images.githubusercontent.com/6548515/57614371-5c354b80-7579-11e9-9362-38986dd09f42.png)

Content of person.yml file:
```
Person:
  required:
    - username
  properties:
    firstName:
      type: string
    lastName:
      type: string
    username:
      type: string
```
Swagger v1.0.27
