### ISSUE TITLE
Array of anyOf items error

### ISSUE THREAD

**Issue by ondratu** [zalando/intellij-swagger#303]
Hi, I have this part of schema:

```yaml
content:
  application/json:
    schema:
      type: object
      properties:
        args:
          type: array
          items:
            anyOf:
              - type: string
              - type: number
              - type: float
              - type: boolean
```
which is valid, but pycharm plugin tell's me missing $ref property
![Snímek z 2020-04-20 13-00-47](https://user-images.githubusercontent.com/6469029/79744719-25c68b80-8307-11ea-9e44-d82bb4f19d04.png)
