### ISSUE TITLE
Autocomplete doesn't work in "Schema Object" 's properties

### ISSUE THREAD

**Issue by sxp** [zalando/intellij-swagger#80]
```
definitions:
  Test:
    type: object
    required:
      - test
    properties:
      test:
        type: // Autocomplete can't work here. Ex. type, format, etc.
```
